# Generated by Django 5.1.15 on 2026-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ui_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский")],
                default="en",
                help_text="The language used for the website interface.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")],
                default="en",
                help_text="Items on shared lists will be translated into this language for you.",
                max_length=10,
            ),
        ),
    ]
