# Generated by Django 5.1.15 on 2026-02-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_ui_language_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                default="en",
                help_text="Items on shared lists will be translated into this language for you.",
                max_length=10,
            ),
        ),
    ]
