# Generated by Django 5.1.15 on 2026-02-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ui_language_alter_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether the user has an active premium subscription.'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for this user.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID for the active subscription.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When the current subscription period ends.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, default='', help_text='Current subscription status (active, canceled, past_due, etc.).', max_length=50),
        ),
    ]
