# Generated by Django 5.1.15 on 2026-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ui_language",
            field=models.CharField(
                default="en",
                help_text="The language used for the website interface.",
                max_length=10,
            ),
        ),
    ]
