# Generated by Django 5.1.15 on 2026-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="source_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")], max_length=10
            ),
        ),
    ]
