# Generated by Django 5.1.15 on 2026-02-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_listitem_source_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listitem", options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="listitem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
