# Generated by Django 5.1.15 on 2026-02-07 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_add_item_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
