# Generated by Django 5.2.11 on 2026-02-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_add_pinned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
