# Generated by Django 5.1.15 on 2026-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_add_list_archived'),
    ]

    operations = [
        # Add composite index on ListItem(list, order) for efficient ordering queries
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'order'], name='lists_item_list_order'),
        ),
    ]
