# Generated by Django 5.1.15 on 2026-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_add_list_archived'),
    ]

    operations = [
        # Add composite index on ListItem(list, order) for efficient ordering queries
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'order'], name='lists_item_list_order'),
        ),
        # Add index on TranslationCache for efficient lookups
        # Note: unique_together already creates an index on (item, target_language)
        # but we also add an index on (item, target_language) for explicit clarity
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['item', 'target_language'], name='lists_trans_item_lang'),
        ),
    ]
