# Generated by Django 5.1.15 on 2026-02-11 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_translationcache_source_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'order'], name='listitem_list_order_idx'),
        ),
    ]
