# Generated by Django 5.1.15 on 2026-02-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_translationcache_source_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="source_language",
            field=models.CharField(max_length=10),
        ),
    ]
