# Generated by Django 5.1.15 on 2026-02-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LanguagePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_code", models.CharField(max_length=10)),
                ("source_name", models.CharField(max_length=100)),
                ("target_code", models.CharField(max_length=10)),
                ("target_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["source_name", "target_name"],
                "unique_together": {("source_code", "target_code")},
            },
        ),
    ]
