# Generated by Django 5.1.15 on 2026-02-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagepair",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
